/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Create {
      
    export type CandidateStruct = {candidateId: BigNumberish, age: string, name: string, image: string, voterCount: BigNumberish, _address: AddressLike, ipfs: string}

    export type CandidateStructOutput = [candidateId: bigint, age: string, name: string, image: string, voterCount: bigint, _address: string, ipfs: string] & {candidateId: bigint, age: string, name: string, image: string, voterCount: bigint, _address: string, ipfs: string }
  

    export type VoterStruct = {voter_voterId: BigNumberish, voter_name: string, voter_image: string, voter_address: AddressLike, voter_allowed: BigNumberish, voter_voted: boolean, voter_vote: BigNumberish, voter_ipfs: string}

    export type VoterStructOutput = [voter_voterId: bigint, voter_name: string, voter_image: string, voter_address: string, voter_allowed: bigint, voter_voted: boolean, voter_vote: bigint, voter_ipfs: string] & {voter_voterId: bigint, voter_name: string, voter_image: string, voter_address: string, voter_allowed: bigint, voter_voted: boolean, voter_vote: bigint, voter_ipfs: string }
  
    }

  export interface CreateInterface extends Interface {
    getFunction(nameOrSignature: "_candidateId" | "_voterId" | "candidateAddress" | "candidates" | "getCandidate" | "getCandidateData" | "getCandidateLength" | "getVotedVoterList" | "getVoterData" | "getVoterLength" | "getVoterList" | "setCandidate" | "vote" | "votedVoters" | "voterRight" | "voters" | "votersAddress" | "votingOrganizer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CandidateCreate" | "VoterCreated"): EventFragment;

    encodeFunctionData(functionFragment: '_candidateId', values?: undefined): string;
encodeFunctionData(functionFragment: '_voterId', values?: undefined): string;
encodeFunctionData(functionFragment: 'candidateAddress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'candidates', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCandidate', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCandidateData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCandidateLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVotedVoterList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVoterData', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVoterLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVoterList', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCandidate', values: [AddressLike, string, string, string, string]): string;
encodeFunctionData(functionFragment: 'vote', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'votedVoters', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voterRight', values: [AddressLike, string, string, string]): string;
encodeFunctionData(functionFragment: 'voters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'votersAddress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'votingOrganizer', values?: undefined): string;

    decodeFunctionResult(functionFragment: '_candidateId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: '_voterId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidateAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCandidateLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVotedVoterList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVoterData', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVoterLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVoterList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votedVoters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voterRight', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votersAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingOrganizer', data: BytesLike): Result;
  }

  
    export namespace CandidateCreateEvent {
      export type InputTuple = [candidateId: BigNumberish, age: string, name: string, image: string, voterCount: BigNumberish, _address: AddressLike, ipfs: string];
      export type OutputTuple = [candidateId: bigint, age: string, name: string, image: string, voterCount: bigint, _address: string, ipfs: string];
      export interface OutputObject {candidateId: bigint, age: string, name: string, image: string, voterCount: bigint, _address: string, ipfs: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterCreatedEvent {
      export type InputTuple = [voter_voterId: BigNumberish, voter_name: string, voter_image: string, voter_address: AddressLike, voter_allowed: BigNumberish, voter_voted: boolean, voter_vote: BigNumberish, voter_ipfs: string];
      export type OutputTuple = [voter_voterId: bigint, voter_name: string, voter_image: string, voter_address: string, voter_allowed: bigint, voter_voted: boolean, voter_vote: bigint, voter_ipfs: string];
      export interface OutputObject {voter_voterId: bigint, voter_name: string, voter_image: string, voter_address: string, voter_allowed: bigint, voter_voted: boolean, voter_vote: bigint, voter_ipfs: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Create extends BaseContract {
    
    connect(runner?: ContractRunner | null): Create;
    waitForDeployment(): Promise<this>;

    interface: CreateInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    _candidateId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    _voterId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    candidateAddress: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    candidates: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, string, string, string, bigint, string, string] & {candidateId: bigint, age: string, name: string, image: string, voterCount: bigint, _address: string, ipfs: string }],
      'view'
    >
    

    
    getCandidate: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getCandidateData: TypedContractMethod<
      [_address: AddressLike, ],
      [Create.CandidateStructOutput],
      'view'
    >
    

    
    getCandidateLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getVotedVoterList: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getVoterData: TypedContractMethod<
      [_address: AddressLike, ],
      [Create.VoterStructOutput],
      'view'
    >
    

    
    getVoterLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getVoterList: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    setCandidate: TypedContractMethod<
      [_address: AddressLike, _age: string, _name: string, _image: string, _ipfs: string, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_candidateAddress: AddressLike, _candidateVoteId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    votedVoters: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    voterRight: TypedContractMethod<
      [_address: AddressLike, name: string, _image: string, _ipfs: string, ],
      [void],
      'nonpayable'
    >
    

    
    voters: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, string, string, string, bigint, boolean, bigint, string] & {voter_voterId: bigint, voter_name: string, voter_image: string, voter_address: string, voter_allowed: bigint, voter_voted: boolean, voter_vote: bigint, voter_ipfs: string }],
      'view'
    >
    

    
    votersAddress: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    votingOrganizer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: '_candidateId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: '_voterId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'candidateAddress'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, string, string, string, bigint, string, string] & {candidateId: bigint, age: string, name: string, image: string, voterCount: bigint, _address: string, ipfs: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidate'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidateData'): TypedContractMethod<
      [_address: AddressLike, ],
      [Create.CandidateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getCandidateLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVotedVoterList'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getVoterData'): TypedContractMethod<
      [_address: AddressLike, ],
      [Create.VoterStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getVoterLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVoterList'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'setCandidate'): TypedContractMethod<
      [_address: AddressLike, _age: string, _name: string, _image: string, _ipfs: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateAddress: AddressLike, _candidateVoteId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votedVoters'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'voterRight'): TypedContractMethod<
      [_address: AddressLike, name: string, _image: string, _ipfs: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, string, string, string, bigint, boolean, bigint, string] & {voter_voterId: bigint, voter_name: string, voter_image: string, voter_address: string, voter_allowed: bigint, voter_voted: boolean, voter_vote: bigint, voter_ipfs: string }],
      'view'
    >;
getFunction(nameOrSignature: 'votersAddress'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'votingOrganizer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CandidateCreate'): TypedContractEvent<CandidateCreateEvent.InputTuple, CandidateCreateEvent.OutputTuple, CandidateCreateEvent.OutputObject>;
getEvent(key: 'VoterCreated'): TypedContractEvent<VoterCreatedEvent.InputTuple, VoterCreatedEvent.OutputTuple, VoterCreatedEvent.OutputObject>;

    filters: {
      
      'CandidateCreate(uint256,string,string,string,uint256,address,string)': TypedContractEvent<CandidateCreateEvent.InputTuple, CandidateCreateEvent.OutputTuple, CandidateCreateEvent.OutputObject>;
      CandidateCreate: TypedContractEvent<CandidateCreateEvent.InputTuple, CandidateCreateEvent.OutputTuple, CandidateCreateEvent.OutputObject>;
    

      'VoterCreated(uint256,string,string,address,uint256,bool,uint256,string)': TypedContractEvent<VoterCreatedEvent.InputTuple, VoterCreatedEvent.OutputTuple, VoterCreatedEvent.OutputObject>;
      VoterCreated: TypedContractEvent<VoterCreatedEvent.InputTuple, VoterCreatedEvent.OutputTuple, VoterCreatedEvent.OutputObject>;
    
    };
  }